[package]
name = "wrap"
version = "0.2.1"
authors = ["David Orchard <if_coding@fastmail.com>"]
edition = "2018"

[dependencies]
# Command line arguments/config
paw = "1"
structopt = { version = "0.3", features = ["paw"] }
enum_derive = "0.1.7"
custom_derive = "0.1.7"

# Config
config = "0.11"
dirs = "3.0.2"
serde_derive = "1.0.126"
serde = "1.0.126"

# Logging/debugging
color-backtrace = "0.5"
log = "0.4"
pretty_env_logger = "0.4"

# Error handling
anyhow = "1"

exec = "0.3.1"
