#!/bin/sh

set -e

# Create a cleanup trap
cleanup() {
    # Re-apply original unstaged changes
    git stash pop -q
}
trap cleanup EXIT

# Stash unstaged changes
git stash -q --keep-index -u

# Run clippy
cargo clippy --fix --allow-staged
cargo clippy -- --deny warnings

# Run clippy
cargo clippy --fix --allow-staged
cargo clippy -- --deny warnings

# Format Nix
nix fmt -- -q .

# Format Rust
cargo fmt

# Stage updated files
git add -u
